// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/v1/discovery.proto

package discoveryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "protogen/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DiscoveryServiceName is the fully-qualified name of the DiscoveryService service.
	DiscoveryServiceName = "neodb.discovery.v1.DiscoveryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DiscoveryServiceGetTablesProcedure is the fully-qualified name of the DiscoveryService's
	// GetTables RPC.
	DiscoveryServiceGetTablesProcedure = "/neodb.discovery.v1.DiscoveryService/GetTables"
	// DiscoveryServiceGetColumnsProcedure is the fully-qualified name of the DiscoveryService's
	// GetColumns RPC.
	DiscoveryServiceGetColumnsProcedure = "/neodb.discovery.v1.DiscoveryService/GetColumns"
)

// DiscoveryServiceClient is a client for the neodb.discovery.v1.DiscoveryService service.
type DiscoveryServiceClient interface {
	GetTables(context.Context, *connect.Request[v1.GetTablesRequest]) (*connect.Response[v1.GetTablesResponse], error)
	GetColumns(context.Context, *connect.Request[v1.GetColumnsRequest]) (*connect.Response[v1.GetColumnsResponse], error)
}

// NewDiscoveryServiceClient constructs a client for the neodb.discovery.v1.DiscoveryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDiscoveryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DiscoveryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	discoveryServiceMethods := v1.File_proto_v1_discovery_proto.Services().ByName("DiscoveryService").Methods()
	return &discoveryServiceClient{
		getTables: connect.NewClient[v1.GetTablesRequest, v1.GetTablesResponse](
			httpClient,
			baseURL+DiscoveryServiceGetTablesProcedure,
			connect.WithSchema(discoveryServiceMethods.ByName("GetTables")),
			connect.WithClientOptions(opts...),
		),
		getColumns: connect.NewClient[v1.GetColumnsRequest, v1.GetColumnsResponse](
			httpClient,
			baseURL+DiscoveryServiceGetColumnsProcedure,
			connect.WithSchema(discoveryServiceMethods.ByName("GetColumns")),
			connect.WithClientOptions(opts...),
		),
	}
}

// discoveryServiceClient implements DiscoveryServiceClient.
type discoveryServiceClient struct {
	getTables  *connect.Client[v1.GetTablesRequest, v1.GetTablesResponse]
	getColumns *connect.Client[v1.GetColumnsRequest, v1.GetColumnsResponse]
}

// GetTables calls neodb.discovery.v1.DiscoveryService.GetTables.
func (c *discoveryServiceClient) GetTables(ctx context.Context, req *connect.Request[v1.GetTablesRequest]) (*connect.Response[v1.GetTablesResponse], error) {
	return c.getTables.CallUnary(ctx, req)
}

// GetColumns calls neodb.discovery.v1.DiscoveryService.GetColumns.
func (c *discoveryServiceClient) GetColumns(ctx context.Context, req *connect.Request[v1.GetColumnsRequest]) (*connect.Response[v1.GetColumnsResponse], error) {
	return c.getColumns.CallUnary(ctx, req)
}

// DiscoveryServiceHandler is an implementation of the neodb.discovery.v1.DiscoveryService service.
type DiscoveryServiceHandler interface {
	GetTables(context.Context, *connect.Request[v1.GetTablesRequest]) (*connect.Response[v1.GetTablesResponse], error)
	GetColumns(context.Context, *connect.Request[v1.GetColumnsRequest]) (*connect.Response[v1.GetColumnsResponse], error)
}

// NewDiscoveryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDiscoveryServiceHandler(svc DiscoveryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	discoveryServiceMethods := v1.File_proto_v1_discovery_proto.Services().ByName("DiscoveryService").Methods()
	discoveryServiceGetTablesHandler := connect.NewUnaryHandler(
		DiscoveryServiceGetTablesProcedure,
		svc.GetTables,
		connect.WithSchema(discoveryServiceMethods.ByName("GetTables")),
		connect.WithHandlerOptions(opts...),
	)
	discoveryServiceGetColumnsHandler := connect.NewUnaryHandler(
		DiscoveryServiceGetColumnsProcedure,
		svc.GetColumns,
		connect.WithSchema(discoveryServiceMethods.ByName("GetColumns")),
		connect.WithHandlerOptions(opts...),
	)
	return "/neodb.discovery.v1.DiscoveryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DiscoveryServiceGetTablesProcedure:
			discoveryServiceGetTablesHandler.ServeHTTP(w, r)
		case DiscoveryServiceGetColumnsProcedure:
			discoveryServiceGetColumnsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDiscoveryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDiscoveryServiceHandler struct{}

func (UnimplementedDiscoveryServiceHandler) GetTables(context.Context, *connect.Request[v1.GetTablesRequest]) (*connect.Response[v1.GetTablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neodb.discovery.v1.DiscoveryService.GetTables is not implemented"))
}

func (UnimplementedDiscoveryServiceHandler) GetColumns(context.Context, *connect.Request[v1.GetColumnsRequest]) (*connect.Response[v1.GetColumnsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neodb.discovery.v1.DiscoveryService.GetColumns is not implemented"))
}
