// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v1/query.proto

package queryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

var File_proto_v1_query_proto protoreflect.FileDescriptor

const file_proto_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/query.proto\x12\x0eneodb.query.v1\"A\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql2\x0e\n" +
	"\fQueryServiceB\x15Z\x13protogen/v1;queryv1b\x06proto3"

var (
	file_proto_v1_query_proto_rawDescOnce sync.Once
	file_proto_v1_query_proto_rawDescData []byte
)

func file_proto_v1_query_proto_rawDescGZIP() []byte {
	file_proto_v1_query_proto_rawDescOnce.Do(func() {
		file_proto_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_query_proto_rawDesc), len(file_proto_v1_query_proto_rawDesc)))
	})
	return file_proto_v1_query_proto_rawDescData
}

var file_proto_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_query_proto_goTypes = []any{
	(*ExecuteRequest)(nil), // 0: neodb.query.v1.ExecuteRequest
}
var file_proto_v1_query_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_query_proto_init() }
func file_proto_v1_query_proto_init() {
	if File_proto_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_query_proto_rawDesc), len(file_proto_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_query_proto_goTypes,
		DependencyIndexes: file_proto_v1_query_proto_depIdxs,
		MessageInfos:      file_proto_v1_query_proto_msgTypes,
	}.Build()
	File_proto_v1_query_proto = out.File
	file_proto_v1_query_proto_goTypes = nil
	file_proto_v1_query_proto_depIdxs = nil
}
