// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package common

import (
	"errors"
	"fmt"
)

const (
	// LoggerFormatText is a LoggerFormat of type Text.
	LoggerFormatText LoggerFormat = iota
	// LoggerFormatJSON is a LoggerFormat of type JSON.
	LoggerFormatJSON
)

var ErrInvalidLoggerFormat = errors.New("not a valid LoggerFormat")

const _LoggerFormatName = "TextJSON"

// LoggerFormatValues returns a list of the values for LoggerFormat
func LoggerFormatValues() []LoggerFormat {
	return []LoggerFormat{
		LoggerFormatText,
		LoggerFormatJSON,
	}
}

var _LoggerFormatMap = map[LoggerFormat]string{
	LoggerFormatText: _LoggerFormatName[0:4],
	LoggerFormatJSON: _LoggerFormatName[4:8],
}

// String implements the Stringer interface.
func (x LoggerFormat) String() string {
	if str, ok := _LoggerFormatMap[x]; ok {
		return str
	}
	return fmt.Sprintf("LoggerFormat(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x LoggerFormat) IsValid() bool {
	_, ok := _LoggerFormatMap[x]
	return ok
}

var _LoggerFormatValue = map[string]LoggerFormat{
	_LoggerFormatName[0:4]: LoggerFormatText,
	_LoggerFormatName[4:8]: LoggerFormatJSON,
}

// ParseLoggerFormat attempts to convert a string to a LoggerFormat.
func ParseLoggerFormat(name string) (LoggerFormat, error) {
	if x, ok := _LoggerFormatValue[name]; ok {
		return x, nil
	}
	return LoggerFormat(0), fmt.Errorf("%s is %w", name, ErrInvalidLoggerFormat)
}

// MarshalText implements the text marshaller method.
func (x LoggerFormat) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *LoggerFormat) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseLoggerFormat(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *LoggerFormat) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// LoggerLevelDebug is a LoggerLevel of type Debug.
	LoggerLevelDebug LoggerLevel = iota + -1
	// LoggerLevelInfo is a LoggerLevel of type Info.
	LoggerLevelInfo
	// LoggerLevelWarn is a LoggerLevel of type Warn.
	LoggerLevelWarn
	// LoggerLevelError is a LoggerLevel of type Error.
	LoggerLevelError
)

var ErrInvalidLoggerLevel = errors.New("not a valid LoggerLevel")

const _LoggerLevelName = "DebugInfoWarnError"

// LoggerLevelValues returns a list of the values for LoggerLevel
func LoggerLevelValues() []LoggerLevel {
	return []LoggerLevel{
		LoggerLevelDebug,
		LoggerLevelInfo,
		LoggerLevelWarn,
		LoggerLevelError,
	}
}

var _LoggerLevelMap = map[LoggerLevel]string{
	LoggerLevelDebug: _LoggerLevelName[0:5],
	LoggerLevelInfo:  _LoggerLevelName[5:9],
	LoggerLevelWarn:  _LoggerLevelName[9:13],
	LoggerLevelError: _LoggerLevelName[13:18],
}

// String implements the Stringer interface.
func (x LoggerLevel) String() string {
	if str, ok := _LoggerLevelMap[x]; ok {
		return str
	}
	return fmt.Sprintf("LoggerLevel(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x LoggerLevel) IsValid() bool {
	_, ok := _LoggerLevelMap[x]
	return ok
}

var _LoggerLevelValue = map[string]LoggerLevel{
	_LoggerLevelName[0:5]:   LoggerLevelDebug,
	_LoggerLevelName[5:9]:   LoggerLevelInfo,
	_LoggerLevelName[9:13]:  LoggerLevelWarn,
	_LoggerLevelName[13:18]: LoggerLevelError,
}

// ParseLoggerLevel attempts to convert a string to a LoggerLevel.
func ParseLoggerLevel(name string) (LoggerLevel, error) {
	if x, ok := _LoggerLevelValue[name]; ok {
		return x, nil
	}
	return LoggerLevel(0), fmt.Errorf("%s is %w", name, ErrInvalidLoggerLevel)
}

// MarshalText implements the text marshaller method.
func (x LoggerLevel) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *LoggerLevel) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseLoggerLevel(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *LoggerLevel) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
