// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v1/discovery.proto

package discoveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableInfo) Reset() {
	*x = TableInfo{}
	mi := &file_proto_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableInfo) ProtoMessage() {}

func (x *TableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableInfo.ProtoReflect.Descriptor instead.
func (*TableInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *TableInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableInfo) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *TableInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ColumnInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IsNullable    bool                   `protobuf:"varint,3,opt,name=is_nullable,json=isNullable,proto3" json:"is_nullable,omitempty"`
	IsPrimaryKey  bool                   `protobuf:"varint,4,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnInfo) Reset() {
	*x = ColumnInfo{}
	mi := &file_proto_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnInfo) ProtoMessage() {}

func (x *ColumnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnInfo.ProtoReflect.Descriptor instead.
func (*ColumnInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ColumnInfo) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *ColumnInfo) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

type GetTablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTablesRequest) Reset() {
	*x = GetTablesRequest{}
	mi := &file_proto_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTablesRequest) ProtoMessage() {}

func (x *GetTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTablesRequest.ProtoReflect.Descriptor instead.
func (*GetTablesRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *GetTablesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetTablesRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type GetTablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*TableInfo           `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTablesResponse) Reset() {
	*x = GetTablesResponse{}
	mi := &file_proto_v1_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTablesResponse) ProtoMessage() {}

func (x *GetTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTablesResponse.ProtoReflect.Descriptor instead.
func (*GetTablesResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *GetTablesResponse) GetTables() []*TableInfo {
	if x != nil {
		return x.Tables
	}
	return nil
}

type GetColumnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TableName     string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Schema        string                 `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetColumnsRequest) Reset() {
	*x = GetColumnsRequest{}
	mi := &file_proto_v1_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColumnsRequest) ProtoMessage() {}

func (x *GetColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColumnsRequest.ProtoReflect.Descriptor instead.
func (*GetColumnsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *GetColumnsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetColumnsRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetColumnsRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type GetColumnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*ColumnInfo          `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetColumnsResponse) Reset() {
	*x = GetColumnsResponse{}
	mi := &file_proto_v1_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetColumnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColumnsResponse) ProtoMessage() {}

func (x *GetColumnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColumnsResponse.ProtoReflect.Descriptor instead.
func (*GetColumnsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *GetColumnsResponse) GetColumns() []*ColumnInfo {
	if x != nil {
		return x.Columns
	}
	return nil
}

var File_proto_v1_discovery_proto protoreflect.FileDescriptor

const file_proto_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/discovery.proto\x12\x12neodb.discovery.v1\"K\n" +
	"\tTableInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"{\n" +
	"\n" +
	"ColumnInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vis_nullable\x18\x03 \x01(\bR\n" +
	"isNullable\x12$\n" +
	"\x0eis_primary_key\x18\x04 \x01(\bR\fisPrimaryKey\"I\n" +
	"\x10GetTablesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\"J\n" +
	"\x11GetTablesResponse\x125\n" +
	"\x06tables\x18\x01 \x03(\v2\x1d.neodb.discovery.v1.TableInfoR\x06tables\"i\n" +
	"\x11GetColumnsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\tR\x06schema\"N\n" +
	"\x12GetColumnsResponse\x128\n" +
	"\acolumns\x18\x01 \x03(\v2\x1e.neodb.discovery.v1.ColumnInfoR\acolumns2\xc9\x01\n" +
	"\x10DiscoveryService\x12X\n" +
	"\tGetTables\x12$.neodb.discovery.v1.GetTablesRequest\x1a%.neodb.discovery.v1.GetTablesResponse\x12[\n" +
	"\n" +
	"GetColumns\x12%.neodb.discovery.v1.GetColumnsRequest\x1a&.neodb.discovery.v1.GetColumnsResponseB\x19Z\x17protogen/v1;discoveryv1b\x06proto3"

var (
	file_proto_v1_discovery_proto_rawDescOnce sync.Once
	file_proto_v1_discovery_proto_rawDescData []byte
)

func file_proto_v1_discovery_proto_rawDescGZIP() []byte {
	file_proto_v1_discovery_proto_rawDescOnce.Do(func() {
		file_proto_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_discovery_proto_rawDesc), len(file_proto_v1_discovery_proto_rawDesc)))
	})
	return file_proto_v1_discovery_proto_rawDescData
}

var file_proto_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_discovery_proto_goTypes = []any{
	(*TableInfo)(nil),          // 0: neodb.discovery.v1.TableInfo
	(*ColumnInfo)(nil),         // 1: neodb.discovery.v1.ColumnInfo
	(*GetTablesRequest)(nil),   // 2: neodb.discovery.v1.GetTablesRequest
	(*GetTablesResponse)(nil),  // 3: neodb.discovery.v1.GetTablesResponse
	(*GetColumnsRequest)(nil),  // 4: neodb.discovery.v1.GetColumnsRequest
	(*GetColumnsResponse)(nil), // 5: neodb.discovery.v1.GetColumnsResponse
}
var file_proto_v1_discovery_proto_depIdxs = []int32{
	0, // 0: neodb.discovery.v1.GetTablesResponse.tables:type_name -> neodb.discovery.v1.TableInfo
	1, // 1: neodb.discovery.v1.GetColumnsResponse.columns:type_name -> neodb.discovery.v1.ColumnInfo
	2, // 2: neodb.discovery.v1.DiscoveryService.GetTables:input_type -> neodb.discovery.v1.GetTablesRequest
	4, // 3: neodb.discovery.v1.DiscoveryService.GetColumns:input_type -> neodb.discovery.v1.GetColumnsRequest
	3, // 4: neodb.discovery.v1.DiscoveryService.GetTables:output_type -> neodb.discovery.v1.GetTablesResponse
	5, // 5: neodb.discovery.v1.DiscoveryService.GetColumns:output_type -> neodb.discovery.v1.GetColumnsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_discovery_proto_init() }
func file_proto_v1_discovery_proto_init() {
	if File_proto_v1_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_discovery_proto_rawDesc), len(file_proto_v1_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_discovery_proto_goTypes,
		DependencyIndexes: file_proto_v1_discovery_proto_depIdxs,
		MessageInfos:      file_proto_v1_discovery_proto_msgTypes,
	}.Build()
	File_proto_v1_discovery_proto = out.File
	file_proto_v1_discovery_proto_goTypes = nil
	file_proto_v1_discovery_proto_depIdxs = nil
}
