// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package neodb

import (
	"errors"
	"fmt"
)

const (
	// ContextKeyConfig is a ContextKey of type config.
	ContextKeyConfig ContextKey = "config"
	// ContextKeyLogger is a ContextKey of type logger.
	ContextKeyLogger ContextKey = "logger"
)

var ErrInvalidContextKey = errors.New("not a valid ContextKey")

// ContextKeyValues returns a list of the values for ContextKey
func ContextKeyValues() []ContextKey {
	return []ContextKey{
		ContextKeyConfig,
		ContextKeyLogger,
	}
}

// String implements the Stringer interface.
func (x ContextKey) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ContextKey) IsValid() bool {
	_, err := ParseContextKey(string(x))
	return err == nil
}

var _ContextKeyValue = map[string]ContextKey{
	"config": ContextKeyConfig,
	"logger": ContextKeyLogger,
}

// ParseContextKey attempts to convert a string to a ContextKey.
func ParseContextKey(name string) (ContextKey, error) {
	if x, ok := _ContextKeyValue[name]; ok {
		return x, nil
	}
	return ContextKey(""), fmt.Errorf("%s is %w", name, ErrInvalidContextKey)
}

// MarshalText implements the text marshaller method.
func (x ContextKey) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ContextKey) UnmarshalText(text []byte) error {
	tmp, err := ParseContextKey(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ContextKey) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
