// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v1/connection.proto

package connectionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	Database      string                 `protobuf:"bytes,8,opt,name=database,proto3" json:"database,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,9,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionProfile) Reset() {
	*x = ConnectionProfile{}
	mi := &file_proto_v1_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionProfile) ProtoMessage() {}

func (x *ConnectionProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionProfile.ProtoReflect.Descriptor instead.
func (*ConnectionProfile) Descriptor() ([]byte, []int) {
	return file_proto_v1_connection_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectionProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectionProfile) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *ConnectionProfile) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectionProfile) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectionProfile) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ConnectionProfile) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConnectionProfile) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ConnectionProfile) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ConnectionProfile     `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_proto_v1_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_connection_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileRequest) GetProfile() *ConnectionProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_proto_v1_connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_connection_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_proto_v1_connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_connection_proto_rawDescGZIP(), []int{3}
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*ConnectionProfile   `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_proto_v1_connection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_connection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_connection_proto_rawDescGZIP(), []int{4}
}

func (x *ListProfilesResponse) GetProfiles() []*ConnectionProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type TestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ConnectionProfile     `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionRequest) Reset() {
	*x = TestConnectionRequest{}
	mi := &file_proto_v1_connection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionRequest) ProtoMessage() {}

func (x *TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_connection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_connection_proto_rawDescGZIP(), []int{5}
}

func (x *TestConnectionRequest) GetProfile() *ConnectionProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type TestConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionResponse) Reset() {
	*x = TestConnectionResponse{}
	mi := &file_proto_v1_connection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionResponse) ProtoMessage() {}

func (x *TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_connection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_connection_proto_rawDescGZIP(), []int{6}
}

func (x *TestConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestConnectionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_v1_connection_proto protoreflect.FileDescriptor

const file_proto_v1_connection_proto_rawDesc = "" +
	"\n" +
	"\x19proto/v1/connection.proto\x12\x13neodb.connection.v1\"\xda\x02\n" +
	"\x11ConnectionProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x03 \x01(\tR\x06driver\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\b \x01(\tR\bdatabase\x12V\n" +
	"\n" +
	"properties\x18\t \x03(\v26.neodb.connection.v1.ConnectionProfile.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x14CreateProfileRequest\x12@\n" +
	"\aprofile\x18\x01 \x01(\v2&.neodb.connection.v1.ConnectionProfileR\aprofile\"'\n" +
	"\x15CreateProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13ListProfilesRequest\"Z\n" +
	"\x14ListProfilesResponse\x12B\n" +
	"\bprofiles\x18\x01 \x03(\v2&.neodb.connection.v1.ConnectionProfileR\bprofiles\"Y\n" +
	"\x15TestConnectionRequest\x12@\n" +
	"\aprofile\x18\x01 \x01(\v2&.neodb.connection.v1.ConnectionProfileR\aprofile\"H\n" +
	"\x16TestConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xcb\x02\n" +
	"\x11ConnectionService\x12f\n" +
	"\rCreateProfile\x12).neodb.connection.v1.CreateProfileRequest\x1a*.neodb.connection.v1.CreateProfileResponse\x12c\n" +
	"\fListProfiles\x12(.neodb.connection.v1.ListProfilesRequest\x1a).neodb.connection.v1.ListProfilesResponse\x12i\n" +
	"\x0eTestConnection\x12*.neodb.connection.v1.TestConnectionRequest\x1a+.neodb.connection.v1.TestConnectionResponseB\x1aZ\x18protogen/v1;connectionv1b\x06proto3"

var (
	file_proto_v1_connection_proto_rawDescOnce sync.Once
	file_proto_v1_connection_proto_rawDescData []byte
)

func file_proto_v1_connection_proto_rawDescGZIP() []byte {
	file_proto_v1_connection_proto_rawDescOnce.Do(func() {
		file_proto_v1_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_connection_proto_rawDesc), len(file_proto_v1_connection_proto_rawDesc)))
	})
	return file_proto_v1_connection_proto_rawDescData
}

var file_proto_v1_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_v1_connection_proto_goTypes = []any{
	(*ConnectionProfile)(nil),      // 0: neodb.connection.v1.ConnectionProfile
	(*CreateProfileRequest)(nil),   // 1: neodb.connection.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),  // 2: neodb.connection.v1.CreateProfileResponse
	(*ListProfilesRequest)(nil),    // 3: neodb.connection.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),   // 4: neodb.connection.v1.ListProfilesResponse
	(*TestConnectionRequest)(nil),  // 5: neodb.connection.v1.TestConnectionRequest
	(*TestConnectionResponse)(nil), // 6: neodb.connection.v1.TestConnectionResponse
	nil,                            // 7: neodb.connection.v1.ConnectionProfile.PropertiesEntry
}
var file_proto_v1_connection_proto_depIdxs = []int32{
	7, // 0: neodb.connection.v1.ConnectionProfile.properties:type_name -> neodb.connection.v1.ConnectionProfile.PropertiesEntry
	0, // 1: neodb.connection.v1.CreateProfileRequest.profile:type_name -> neodb.connection.v1.ConnectionProfile
	0, // 2: neodb.connection.v1.ListProfilesResponse.profiles:type_name -> neodb.connection.v1.ConnectionProfile
	0, // 3: neodb.connection.v1.TestConnectionRequest.profile:type_name -> neodb.connection.v1.ConnectionProfile
	1, // 4: neodb.connection.v1.ConnectionService.CreateProfile:input_type -> neodb.connection.v1.CreateProfileRequest
	3, // 5: neodb.connection.v1.ConnectionService.ListProfiles:input_type -> neodb.connection.v1.ListProfilesRequest
	5, // 6: neodb.connection.v1.ConnectionService.TestConnection:input_type -> neodb.connection.v1.TestConnectionRequest
	2, // 7: neodb.connection.v1.ConnectionService.CreateProfile:output_type -> neodb.connection.v1.CreateProfileResponse
	4, // 8: neodb.connection.v1.ConnectionService.ListProfiles:output_type -> neodb.connection.v1.ListProfilesResponse
	6, // 9: neodb.connection.v1.ConnectionService.TestConnection:output_type -> neodb.connection.v1.TestConnectionResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_connection_proto_init() }
func file_proto_v1_connection_proto_init() {
	if File_proto_v1_connection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_connection_proto_rawDesc), len(file_proto_v1_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_connection_proto_goTypes,
		DependencyIndexes: file_proto_v1_connection_proto_depIdxs,
		MessageInfos:      file_proto_v1_connection_proto_msgTypes,
	}.Build()
	File_proto_v1_connection_proto = out.File
	file_proto_v1_connection_proto_goTypes = nil
	file_proto_v1_connection_proto_depIdxs = nil
}
