// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/v1/connection.proto

package connectionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "protogen/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConnectionServiceName is the fully-qualified name of the ConnectionService service.
	ConnectionServiceName = "neodb.connection.v1.ConnectionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConnectionServiceCreateProfileProcedure is the fully-qualified name of the ConnectionService's
	// CreateProfile RPC.
	ConnectionServiceCreateProfileProcedure = "/neodb.connection.v1.ConnectionService/CreateProfile"
	// ConnectionServiceListProfilesProcedure is the fully-qualified name of the ConnectionService's
	// ListProfiles RPC.
	ConnectionServiceListProfilesProcedure = "/neodb.connection.v1.ConnectionService/ListProfiles"
	// ConnectionServiceTestConnectionProcedure is the fully-qualified name of the ConnectionService's
	// TestConnection RPC.
	ConnectionServiceTestConnectionProcedure = "/neodb.connection.v1.ConnectionService/TestConnection"
)

// ConnectionServiceClient is a client for the neodb.connection.v1.ConnectionService service.
type ConnectionServiceClient interface {
	CreateProfile(context.Context, *connect.Request[v1.CreateProfileRequest]) (*connect.Response[v1.CreateProfileResponse], error)
	ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error)
	TestConnection(context.Context, *connect.Request[v1.TestConnectionRequest]) (*connect.Response[v1.TestConnectionResponse], error)
}

// NewConnectionServiceClient constructs a client for the neodb.connection.v1.ConnectionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConnectionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConnectionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	connectionServiceMethods := v1.File_proto_v1_connection_proto.Services().ByName("ConnectionService").Methods()
	return &connectionServiceClient{
		createProfile: connect.NewClient[v1.CreateProfileRequest, v1.CreateProfileResponse](
			httpClient,
			baseURL+ConnectionServiceCreateProfileProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("CreateProfile")),
			connect.WithClientOptions(opts...),
		),
		listProfiles: connect.NewClient[v1.ListProfilesRequest, v1.ListProfilesResponse](
			httpClient,
			baseURL+ConnectionServiceListProfilesProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("ListProfiles")),
			connect.WithClientOptions(opts...),
		),
		testConnection: connect.NewClient[v1.TestConnectionRequest, v1.TestConnectionResponse](
			httpClient,
			baseURL+ConnectionServiceTestConnectionProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("TestConnection")),
			connect.WithClientOptions(opts...),
		),
	}
}

// connectionServiceClient implements ConnectionServiceClient.
type connectionServiceClient struct {
	createProfile  *connect.Client[v1.CreateProfileRequest, v1.CreateProfileResponse]
	listProfiles   *connect.Client[v1.ListProfilesRequest, v1.ListProfilesResponse]
	testConnection *connect.Client[v1.TestConnectionRequest, v1.TestConnectionResponse]
}

// CreateProfile calls neodb.connection.v1.ConnectionService.CreateProfile.
func (c *connectionServiceClient) CreateProfile(ctx context.Context, req *connect.Request[v1.CreateProfileRequest]) (*connect.Response[v1.CreateProfileResponse], error) {
	return c.createProfile.CallUnary(ctx, req)
}

// ListProfiles calls neodb.connection.v1.ConnectionService.ListProfiles.
func (c *connectionServiceClient) ListProfiles(ctx context.Context, req *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error) {
	return c.listProfiles.CallUnary(ctx, req)
}

// TestConnection calls neodb.connection.v1.ConnectionService.TestConnection.
func (c *connectionServiceClient) TestConnection(ctx context.Context, req *connect.Request[v1.TestConnectionRequest]) (*connect.Response[v1.TestConnectionResponse], error) {
	return c.testConnection.CallUnary(ctx, req)
}

// ConnectionServiceHandler is an implementation of the neodb.connection.v1.ConnectionService
// service.
type ConnectionServiceHandler interface {
	CreateProfile(context.Context, *connect.Request[v1.CreateProfileRequest]) (*connect.Response[v1.CreateProfileResponse], error)
	ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error)
	TestConnection(context.Context, *connect.Request[v1.TestConnectionRequest]) (*connect.Response[v1.TestConnectionResponse], error)
}

// NewConnectionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConnectionServiceHandler(svc ConnectionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	connectionServiceMethods := v1.File_proto_v1_connection_proto.Services().ByName("ConnectionService").Methods()
	connectionServiceCreateProfileHandler := connect.NewUnaryHandler(
		ConnectionServiceCreateProfileProcedure,
		svc.CreateProfile,
		connect.WithSchema(connectionServiceMethods.ByName("CreateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceListProfilesHandler := connect.NewUnaryHandler(
		ConnectionServiceListProfilesProcedure,
		svc.ListProfiles,
		connect.WithSchema(connectionServiceMethods.ByName("ListProfiles")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceTestConnectionHandler := connect.NewUnaryHandler(
		ConnectionServiceTestConnectionProcedure,
		svc.TestConnection,
		connect.WithSchema(connectionServiceMethods.ByName("TestConnection")),
		connect.WithHandlerOptions(opts...),
	)
	return "/neodb.connection.v1.ConnectionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConnectionServiceCreateProfileProcedure:
			connectionServiceCreateProfileHandler.ServeHTTP(w, r)
		case ConnectionServiceListProfilesProcedure:
			connectionServiceListProfilesHandler.ServeHTTP(w, r)
		case ConnectionServiceTestConnectionProcedure:
			connectionServiceTestConnectionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConnectionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConnectionServiceHandler struct{}

func (UnimplementedConnectionServiceHandler) CreateProfile(context.Context, *connect.Request[v1.CreateProfileRequest]) (*connect.Response[v1.CreateProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neodb.connection.v1.ConnectionService.CreateProfile is not implemented"))
}

func (UnimplementedConnectionServiceHandler) ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neodb.connection.v1.ConnectionService.ListProfiles is not implemented"))
}

func (UnimplementedConnectionServiceHandler) TestConnection(context.Context, *connect.Request[v1.TestConnectionRequest]) (*connect.Response[v1.TestConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neodb.connection.v1.ConnectionService.TestConnection is not implemented"))
}
