// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/v1/session.proto

package sessionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "protogen/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "neodb.session.v1.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceCreateSessionProcedure is the fully-qualified name of the SessionService's
	// CreateSession RPC.
	SessionServiceCreateSessionProcedure = "/neodb.session.v1.SessionService/CreateSession"
	// SessionServiceCloseSessionProcedure is the fully-qualified name of the SessionService's
	// CloseSession RPC.
	SessionServiceCloseSessionProcedure = "/neodb.session.v1.SessionService/CloseSession"
	// SessionServiceGetHistoryProcedure is the fully-qualified name of the SessionService's GetHistory
	// RPC.
	SessionServiceGetHistoryProcedure = "/neodb.session.v1.SessionService/GetHistory"
)

// SessionServiceClient is a client for the neodb.session.v1.SessionService service.
type SessionServiceClient interface {
	CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error)
	CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error)
	GetHistory(context.Context, *connect.Request[v1.GetHistoryRequest]) (*connect.Response[v1.GetHistoryResponse], error)
}

// NewSessionServiceClient constructs a client for the neodb.session.v1.SessionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := v1.File_proto_v1_session_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		createSession: connect.NewClient[v1.CreateSessionRequest, v1.CreateSessionResponse](
			httpClient,
			baseURL+SessionServiceCreateSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		closeSession: connect.NewClient[v1.CloseSessionRequest, v1.CloseSessionResponse](
			httpClient,
			baseURL+SessionServiceCloseSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("CloseSession")),
			connect.WithClientOptions(opts...),
		),
		getHistory: connect.NewClient[v1.GetHistoryRequest, v1.GetHistoryResponse](
			httpClient,
			baseURL+SessionServiceGetHistoryProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetHistory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	createSession *connect.Client[v1.CreateSessionRequest, v1.CreateSessionResponse]
	closeSession  *connect.Client[v1.CloseSessionRequest, v1.CloseSessionResponse]
	getHistory    *connect.Client[v1.GetHistoryRequest, v1.GetHistoryResponse]
}

// CreateSession calls neodb.session.v1.SessionService.CreateSession.
func (c *sessionServiceClient) CreateSession(ctx context.Context, req *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// CloseSession calls neodb.session.v1.SessionService.CloseSession.
func (c *sessionServiceClient) CloseSession(ctx context.Context, req *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error) {
	return c.closeSession.CallUnary(ctx, req)
}

// GetHistory calls neodb.session.v1.SessionService.GetHistory.
func (c *sessionServiceClient) GetHistory(ctx context.Context, req *connect.Request[v1.GetHistoryRequest]) (*connect.Response[v1.GetHistoryResponse], error) {
	return c.getHistory.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the neodb.session.v1.SessionService service.
type SessionServiceHandler interface {
	CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error)
	CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error)
	GetHistory(context.Context, *connect.Request[v1.GetHistoryRequest]) (*connect.Response[v1.GetHistoryResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := v1.File_proto_v1_session_proto.Services().ByName("SessionService").Methods()
	sessionServiceCreateSessionHandler := connect.NewUnaryHandler(
		SessionServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(sessionServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceCloseSessionHandler := connect.NewUnaryHandler(
		SessionServiceCloseSessionProcedure,
		svc.CloseSession,
		connect.WithSchema(sessionServiceMethods.ByName("CloseSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetHistoryHandler := connect.NewUnaryHandler(
		SessionServiceGetHistoryProcedure,
		svc.GetHistory,
		connect.WithSchema(sessionServiceMethods.ByName("GetHistory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/neodb.session.v1.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceCreateSessionProcedure:
			sessionServiceCreateSessionHandler.ServeHTTP(w, r)
		case SessionServiceCloseSessionProcedure:
			sessionServiceCloseSessionHandler.ServeHTTP(w, r)
		case SessionServiceGetHistoryProcedure:
			sessionServiceGetHistoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neodb.session.v1.SessionService.CreateSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neodb.session.v1.SessionService.CloseSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetHistory(context.Context, *connect.Request[v1.GetHistoryRequest]) (*connect.Response[v1.GetHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neodb.session.v1.SessionService.GetHistory is not implemented"))
}
